name: SwagMeli Config Scanner

on:
  schedule:
    - cron: '0 * * * *' # هر یک ساعت یک‌بار اجرا می‌شود
  workflow_dispatch: # دکمه اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # اجازه قطعی برای نوشتن در مخزن
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # دریافت کل تاریخچه برای جلوگیری از ارور Push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Scanner
        run: python Trash/scanner_v2.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # تلاش برای دریافت تغییرات احتمالی قبل از فرستادن
          git pull origin main --rebase
          
          # اضافه کردن فایل خروجی
          git add main/final.txt
          
          # کامیت کردن (اگر تغییری نبود ارور ندهد)
          git commit -m "Update final configs [Automated]" || echo "No changes to commit"
          
          # فرستادن با تلاش مجدد در صورت خطا
          git push origin main || (git pull origin main --rebase && git push origin main)
